//
//  MovieDetailWorker.swift
//  PopcornHub
//
//  Created by Diego Escamilla on 30/07/21.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol MovieDetailWorkerInterface {
    
}

class MovieDetailWorker: MovieDetailWorkerInterface {

}
