//
//  MovieDetailModels.swift
//  PopcornHub
//
//  Created by Diego Escamilla on 30/07/21.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetailModels {
    
    // MARK: Use cases
    
    enum FetchMovieDetail {
        
        struct Request {
        }
        
        struct Response {
			var movieDetail: MediaResult
        }
        
        struct ViewModel {
			var backdropImage: String
			var title: String
			var language: String
			var date: String
			var averageVotes: String
			var totalVotes: String
			var overview: String
        }
    }
}
