//
//  MovieDetailPresenter.swift
//  PopcornHub
//
//  Created by Diego Escamilla on 30/07/21.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresenterInterface {
    func presentMovieDetail(response: MovieDetailModels.FetchMovieDetail.Response)
}

class MovieDetailPresenter: MovieDetailPresenterInterface {
    
    // MARK: - Properties
    
    weak var viewController: MovieDetailDisplayInterface?
    
    // MARK: - MovieDetailPresenterInterface
    
    func presentMovieDetail(response: MovieDetailModels.FetchMovieDetail.Response) {
		let viewModel = MovieDetailModels.FetchMovieDetail.ViewModel(backdropImage: response.movieDetail.backdropPath ?? (response.movieDetail.posterPath ?? ""),
																	 title: response.movieDetail.title ?? LocalStrings.Common.doNotExist,
																	 language: response.movieDetail.originalLanguage ?? LocalStrings.Common.doNotExist,
																	 date: response.movieDetail.releaseeDate ?? LocalStrings.Common.doNotExist,
																	 averageVotes: String(response.movieDetail.voteAverage ?? 0),
																	 totalVotes: String(response.movieDetail.voteCount ?? 0),
																	 overview: response.movieDetail.overview ?? LocalStrings.Common.doNotExist)
        viewController?.displayMovieDetail(viewModel: viewModel)
    }
}
