//
//  PopularMoviesPresenterTests.swift
//  PopcornHub
//
//  Created by Diego Escamilla on 01/08/21.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import PopcornHub
import XCTest

class PopularMoviesPresenterTests: XCTestCase {
    
    // MARK: Subject under test
    
    var sut: PopularMoviesPresenter!
	var spyViewController: PopularMoviesViewcontrollerSpy!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupPopularMoviesPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupPopularMoviesPresenter() {
        sut = PopularMoviesPresenter()
		spyViewController = PopularMoviesViewcontrollerSpy()
		sut.viewController = spyViewController
    }
    
    // MARK: Tests
    
    func testPresentPopularMovies() {
        // Given
		let mediaList = Dummies.Common.getMediaList()
		let response = PopularMoviesModels.FetchPopularMovies.Response(mediaList: mediaList)
        
        // When
		sut.presentPopularMovies(response: response)
        
        // Then
		XCTAssert(spyViewController.displayPopularMoviesCalled)
		XCTAssertEqual(spyViewController.displayPopularMoviesViewModel?.displayableMediaList.count, mediaList.count)
    }
	
	func testPresentMovieDetail() {
		// When
		sut.presentMovieDetail()
		
		// Then
		XCTAssert(spyViewController.displayMovieDetailCalled)
	}
}

// MARK: Test doubles

class PopularMoviesViewcontrollerSpy: PopularMoviesDisplayInterface {
	var displayPopularMoviesCalled = false
	var displayPopularMoviesViewModel: PopularMoviesModels.FetchPopularMovies.ViewModel?
	func displayPopularMovies(popularMoviesViewModel: PopularMoviesModels.FetchPopularMovies.ViewModel) {
		displayPopularMoviesCalled = true
		displayPopularMoviesViewModel = popularMoviesViewModel
	}
	
	var displayMovieDetailCalled = false
	func displayMovieDetail() {
		displayMovieDetailCalled = true
	}
}
