//
//  TopRatedMoviesRouter.swift
//  PopcornHub
//
//  Created by Diego Escamilla on 27/07/21.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopRatedMoviesRouterInterface {
    func routeToMovieDetail()
}

protocol TopRatedMoviesDataPassing {
    var dataStore: TopRatedMoviesDataStore? { get }
}

class TopRatedMoviesRouter: TopRatedMoviesRouterInterface, TopRatedMoviesDataPassing {
    
    // MARK: - Properties
    
    weak var viewController: TopRatedMoviesViewController?
    var dataStore: TopRatedMoviesDataStore?
	
	func routeToMovieDetail() {
		let popularMovieViewController = MovieDetailViewController(nibName: NibNames.MovieDetail, bundle: nil)
		guard let sourceDataStore = dataStore,
			  var destinationDataStore = popularMovieViewController.router?.dataStore else {
			return
		}
		passDataToPopularMovieDetail(source: sourceDataStore, destination: &destinationDataStore)
		viewController?.present(popularMovieViewController, animated: true, completion: nil)
	}
	
	private func passDataToPopularMovieDetail(source: TopRatedMoviesDataStore, destination: inout MovieDetailDataStore) {
		destination.movieDetail = source.selectedMovie
	}
}
