//
//  PopularMoviesModels.swift
//  PopcornHub
//
//  Created by Diego Escamilla on 27/07/21.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PopularMoviesModels {
	
	// MARK: Use cases
	
	enum FetchPopularMovies {
		
		struct Request {
			var page = 1
		}
		
		struct Response {
			var mediaList = [MediaResult]()
			var error: Error?
		}
		
		struct ViewModel {
			var displayableMediaList = [DisplayablePopularMovie]()
		}
	}
	
	enum CachePopularMovies {
		struct Request {
			var popularMoviesList = [MediaResult]()
		}
	}
	
	enum SelectMovie {
		struct Request {
			var index: Int
		}
	}
	
	enum SearchMovieDetail {
		struct Request {
			var searchString: String?
		}
	}
}
