//
//  PopularMoviesPresenter.swift
//  PopcornHub
//
//  Created by Diego Escamilla on 27/07/21.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PopularMoviesPresenterInterface {
	func presentPopularMovies(response: PopularMoviesModels.FetchPopularMovies.Response)
	func presentMovieDetail()
}

class PopularMoviesPresenter: PopularMoviesPresenterInterface {
	
	// MARK: - Properties
	
	weak var viewController: PopularMoviesDisplayInterface?
	
	// MARK: - PopularMoviesPresenterInterface
	
	func presentPopularMovies(response: PopularMoviesModels.FetchPopularMovies.Response) {
		let displayableMediaList = getDisplayableMediaList(mediaList: response.mediaList)
		let viewModel = PopularMoviesModels.FetchPopularMovies.ViewModel(displayableMediaList: displayableMediaList)
		viewController?.displayPopularMovies(popularMoviesViewModel: viewModel)
	}
	
	func presentMovieDetail() {
		viewController?.displayMovieDetail()
	}
	
	private func getDisplayableMediaList(mediaList: [MediaResult]) -> [DisplayablePopularMovie] {
		mediaList.map { mediaResult in
			let title = mediaResult.title ?? LocalStrings.Common.doNotExist
			let date = LocalStrings.MediaCell.dateKeyLabel + (mediaResult.releaseeDate ?? LocalStrings.Common.doNotExist)
			let popularity = LocalStrings.MediaCell.popularityKeyLabel + (mediaResult.popularity == nil ? LocalStrings.Common.doNotExist : String(mediaResult.popularity ?? 0))
			let image = mediaResult.posterPath ?? ""
			return DisplayablePopularMovie(title: title, firstInformationData: date, secondInformationData: popularity, mediaImageUrl: image, mediaSection: .Popular)
		}
	}
}
