//
//  TopRatedMoviesPresenterTests.swift
//  PopcornHub
//
//  Created by Diego Escamilla on 02/08/21.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import PopcornHub
import XCTest

class TopRatedMoviesPresenterTests: XCTestCase {
    
    // MARK: Subject under test
    
    var sut: TopRatedMoviesPresenter!
	var viewControllerSpy: TopRatedMoviesViewControllerSpy!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupTopRatedMoviesPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    func setupTopRatedMoviesPresenter() {
        sut = TopRatedMoviesPresenter()
		viewControllerSpy = TopRatedMoviesViewControllerSpy()
		sut.viewController = viewControllerSpy
    }
    
    // MARK: Tests
    
    func testPresentTopRatedMovies() {
        // Given
		let mediaList = Dummies.Common.getMediaList()
        let response = TopRatedMoviesModels.FetchTopRatedMovies.Response(mediaList: mediaList)
		
        // When
		sut.presentTopRatedMovies(response: response)
        
        // Then
		XCTAssert(viewControllerSpy?.displayTopRatedMoviesCalled ?? false)
		XCTAssertEqual(viewControllerSpy?.displayTopRatedMoviesViewModel?.displayableMediaList.count, mediaList.count)
    }
	
	func testPresentSelectedTopRatedMovie() {
		// When
		sut.presentSelectedTopRatedMovie()
		
		// Then
		XCTAssert(viewControllerSpy?.displaySelectedMovieCalled ?? false)
	}
}

// MARK: Test doubles

class TopRatedMoviesViewControllerSpy: TopRatedMoviesDisplayInterface {
	var displayTopRatedMoviesCalled = false
	var displayTopRatedMoviesViewModel: TopRatedMoviesModels.FetchTopRatedMovies.ViewModel?
	func displayTopRatedMovies(topRatedMoviesViewModel: TopRatedMoviesModels.FetchTopRatedMovies.ViewModel) {
		displayTopRatedMoviesCalled = true
		displayTopRatedMoviesViewModel = topRatedMoviesViewModel
	}
	
	var displaySelectedMovieCalled = false
	func displaySelectedMovie() {
		displaySelectedMovieCalled = true
	}
}
